# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ChannelSnapshotSoloTx do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel_id",
    :"from_id",
    :"payload",
    :"ttl",
    :"fee",
    :"nonce"
  ]

  @type t :: %__MODULE__{
    :"channel_id" => EncodedHash,
    :"from_id" => EncodedHash,
    :"payload" => String.t,
    :"ttl" => integer(),
    :"fee" => integer(),
    :"nonce" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ChannelSnapshotSoloTx do

  def decode(value, options) do
    value
  end
end

