# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ChannelForceProgressTxJson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel_id",
    :"from_id",
    :"payload",
    :"round",
    :"update",
    :"state_hash",
    :"ttl",
    :"fee",
    :"nonce",
    :"offchain_trees",
    :"version",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"channel_id" => EncodedHash,
    :"from_id" => EncodedHash,
    :"payload" => String.t,
    :"round" => integer(),
    :"update" => OffChainUpdate,
    :"state_hash" => EncodedHash,
    :"ttl" => integer(),
    :"fee" => integer(),
    :"nonce" => integer(),
    :"offchain_trees" => EncodedHash,
    :"version" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ChannelForceProgressTxJson do

  def decode(value, options) do
    value
  end
end

