# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.Channel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"initiator_id",
    :"responder_id",
    :"channel_amount",
    :"initiator_amount",
    :"responder_amount",
    :"channel_reserve",
    :"delegate_ids",
    :"state_hash",
    :"round",
    :"solo_round",
    :"lock_period",
    :"locked_until"
  ]

  @type t :: %__MODULE__{
    :"id" => EncodedHash,
    :"initiator_id" => EncodedHash,
    :"responder_id" => EncodedHash,
    :"channel_amount" => integer(),
    :"initiator_amount" => integer(),
    :"responder_amount" => integer(),
    :"channel_reserve" => integer(),
    :"delegate_ids" => [EncodedHash],
    :"state_hash" => EncodedHash,
    :"round" => integer(),
    :"solo_round" => integer(),
    :"lock_period" => integer(),
    :"locked_until" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.Channel do

  def decode(value, options) do
    value
  end
end

