# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ChannelDepositTxJson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel_id",
    :"from_id",
    :"amount",
    :"ttl",
    :"fee",
    :"nonce",
    :"state_hash",
    :"round",
    :"version",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"channel_id" => EncodedHash,
    :"from_id" => EncodedHash,
    :"amount" => integer(),
    :"ttl" => integer(),
    :"fee" => integer(),
    :"nonce" => integer(),
    :"state_hash" => EncodedHash,
    :"round" => integer(),
    :"version" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ChannelDepositTxJson do
 
  def decode(value, options) do
    value
  end
end

