# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ChannelWithdrawTx do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel_id",
    :"to_id",
    :"amount",
    :"ttl",
    :"fee",
    :"nonce",
    :"state_hash",
    :"round"
  ]

  @type t :: %__MODULE__{
    :"channel_id" => EncodedHash,
    :"to_id" => EncodedHash,
    :"amount" => integer(),
    :"ttl" => integer(),
    :"fee" => integer(),
    :"nonce" => integer(),
    :"state_hash" => EncodedHash,
    :"round" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ChannelWithdrawTx do

  def decode(value, options) do
    value
  end
end

