# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ChannelCreateTxJson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"initiator_id",
    :"initiator_amount",
    :"responder_id",
    :"responder_amount",
    :"push_amount",
    :"channel_reserve",
    :"lock_period",
    :"ttl",
    :"fee",
    :"nonce",
    :"state_hash",
    :"version",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"initiator_id" => EncodedHash,
    :"initiator_amount" => integer(),
    :"responder_id" => EncodedHash,
    :"responder_amount" => integer(),
    :"push_amount" => integer(),
    :"channel_reserve" => integer(),
    :"lock_period" => integer(),
    :"ttl" => integer(),
    :"fee" => integer(),
    :"nonce" => integer(),
    :"state_hash" => EncodedHash,
    :"version" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ChannelCreateTxJson do

  def decode(value, options) do
    value
  end
end

