# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.CommitmentId do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"commitment_id"
  ]

  @type t :: %__MODULE__{
    :"commitment_id" => EncodedHash
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.CommitmentId do

  def decode(value, options) do
    value
  end
end

