# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractStoreStore do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"value" => EncodedByteArray
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractStoreStore do

  def decode(value, options) do
    value
  end
end

