# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractCallObject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"caller_id",
    :"caller_nonce",
    :"height",
    :"contract_id",
    :"gas_price",
    :"gas_used",
    :"return_value",
    :"return_type"
  ]

  @type t :: %__MODULE__{
    :"caller_id" => EncodedHash,
    :"caller_nonce" => integer(),
    :"height" => integer(),
    :"contract_id" => EncodedHash,
    :"gas_price" => integer(),
    :"gas_used" => integer(),
    :"return_value" => EncodedByteArray,
    :"return_type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractCallObject do
 
  def decode(value, options) do
    value
  end
end

