# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractCallCompute do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"caller_id",
    :"nonce",
    :"contract_id",
    :"vm_version",
    :"fee",
    :"ttl",
    :"amount",
    :"gas",
    :"gas_price",
    :"function",
    :"arguments",
    :"call"
  ]

  @type t :: %__MODULE__{
    :"caller_id" => EncodedHash,
    :"nonce" => integer(),
    :"contract_id" => EncodedHash,
    :"vm_version" => integer(),
    :"fee" => integer(),
    :"ttl" => integer(),
    :"amount" => integer(),
    :"gas" => integer(),
    :"gas_price" => integer(),
    :"function" => String.t,
    :"arguments" => String.t,
    :"call" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractCallCompute do

  def decode(value, options) do
    value
  end
end

