# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractObject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"owner_id",
    :"vm_version",
    :"log",
    :"active",
    :"referrer_ids",
    :"deposit"
  ]

  @type t :: %__MODULE__{
    :"id" => EncodedHash,
    :"owner_id" => EncodedHash,
    :"vm_version" => integer(),
    :"log" => String.t,
    :"active" => boolean(),
    :"referrer_ids" => [EncodedHash],
    :"deposit" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractObject do

  def decode(value, options) do
    value
  end
end

