# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractCreateTxJson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"owner_id",
    :"nonce",
    :"code",
    :"vm_version",
    :"deposit",
    :"amount",
    :"gas",
    :"gas_price",
    :"fee",
    :"ttl",
    :"call_data",
    :"version",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"owner_id" => EncodedHash,
    :"nonce" => integer(),
    :"code" => String.t,
    :"vm_version" => integer(),
    :"deposit" => integer(),
    :"amount" => integer(),
    :"gas" => integer(),
    :"gas_price" => integer(),
    :"fee" => integer(),
    :"ttl" => integer(),
    :"call_data" => EncodedByteArray,
    :"version" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractCreateTxJson do

  def decode(value, options) do
    value
  end
end

