# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.ContractStore do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"store"
  ]

  @type t :: %__MODULE__{
    :"store" => [ContractStoreStore]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.ContractStore do

  def decode(value, options) do
    value
  end
end

