# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.CreateContractUnsignedTx do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"tx",
    :"contract_id"
  ]

  @type t :: %__MODULE__{
    :"tx" => EncodedHash,
    :"contract_id" => EncodedHash
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.CreateContractUnsignedTx do
 
  def decode(value, options) do
    value
  end
end

