# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.DryRunInput do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"top",
    :"accounts",
    :"txs"
  ]

  @type t :: %__MODULE__{
    :"top" => String.t,
    :"accounts" => [DryRunAccount],
    :"txs" => [EncodedHash]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.DryRunInput do

  def decode(value, options) do
    value
  end
end

