# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.GenericSignedTx do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"tx",
    :"block_height",
    :"block_hash",
    :"hash",
    :"signatures"
  ]

  @type t :: %__MODULE__{
    :"tx" => GenericTx,
    :"block_height" => integer(),
    :"block_hash" => EncodedHash,
    :"hash" => EncodedHash,
    :"signatures" => [String.t]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.GenericSignedTx do

  def decode(value, options) do
    value
  end
end

