# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.KeyBlockOrMicroBlockHeader do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"key_block",
    :"micro_block"
  ]

  @type t :: %__MODULE__{
    :"key_block" => KeyBlock,
    :"micro_block" => MicroBlockHeader
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.KeyBlockOrMicroBlockHeader do

  def decode(value, options) do
    value
  end
end

