# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.NameEntry do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"ttl",
    :"pointers"
  ]

  @type t :: %__MODULE__{
    :"id" => EncodedHash,
    :"ttl" => integer(),
    :"pointers" => [NamePointer]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.NameEntry do

  def decode(value, options) do
    value
  end
end

