# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.NameClaimTx do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"name_salt",
    :"fee",
    :"ttl",
    :"account_id",
    :"nonce"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"name_salt" => integer(),
    :"fee" => integer(),
    :"ttl" => integer(),
    :"account_id" => EncodedHash,
    :"nonce" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.NameClaimTx do

  def decode(value, options) do
    value
  end
end

