# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.NamePointer do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :id
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :id => EncodedHash
        }
end

defimpl Poison.Decoder, for: AeternityNode.Model.NamePointer do
  def decode(value, options) do
    value
  end
end
