# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.OffChainNewContract do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :op,
    :owner,
    :vm_version,
    :code,
    :deposit,
    :call_data
  ]

  @type t :: %__MODULE__{
          :op => String.t(),
          :owner => EncodedHash,
          :vm_version => integer(),
          :code => ByteCode,
          :deposit => integer(),
          :call_data => EncodedByteArray
        }
end

defimpl Poison.Decoder, for: AeternityNode.Model.OffChainNewContract do
  def decode(value, options) do
    value
  end
end
