# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.OffChainTransfer do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"op",
    :"from",
    :"to",
    :"am"
  ]

  @type t :: %__MODULE__{
    :"op" => String.t,
    :"from" => EncodedHash,
    :"to" => EncodedHash,
    :"am" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.OffChainTransfer do

  def decode(value, options) do
    value
  end
end

