# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.OracleRegisterTxJson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"query_format",
    :"response_format",
    :"query_fee",
    :"oracle_ttl",
    :"account_id",
    :"nonce",
    :"fee",
    :"ttl",
    :"vm_version",
    :"version",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"query_format" => String.t,
    :"response_format" => String.t,
    :"query_fee" => integer(),
    :"oracle_ttl" => Ttl,
    :"account_id" => EncodedHash,
    :"nonce" => integer(),
    :"fee" => integer(),
    :"ttl" => integer(),
    :"vm_version" => integer(),
    :"version" => integer(),
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.OracleRegisterTxJson do

  def decode(value, options) do
    value
  end
end

