# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.OracleQuery do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :sender_id,
    :sender_nonce,
    :oracle_id,
    :query,
    :response,
    :ttl,
    :response_ttl,
    :fee
  ]

  @type t :: %__MODULE__{
          :id => EncodedHash,
          :sender_id => EncodedHash,
          :sender_nonce => integer(),
          :oracle_id => EncodedHash,
          :query => String.t(),
          :response => String.t(),
          :ttl => integer(),
          :response_ttl => Ttl,
          :fee => integer()
        }
end

defimpl Poison.Decoder, for: AeternityNode.Model.OracleQuery do
  def decode(value, options) do
    value
  end
end
