# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.OracleQueries do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"oracle_queries"
  ]

  @type t :: %__MODULE__{
    :"oracle_queries" => [OracleQuery]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.OracleQueries do

  def decode(value, options) do
    value
  end
end

