# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.Peers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"peers",
    :"blocked"
  ]

  @type t :: %__MODULE__{
    :"peers" => [Peer],
    :"blocked" => [Peer]
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.Peers do

  def decode(value, options) do
    value
  end
end

