# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.RegisteredOracle do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"query_format",
    :"response_format",
    :"query_fee",
    :"ttl",
    :"vm_version"
  ]

  @type t :: %__MODULE__{
    :"id" => EncodedHash,
    :"query_format" => String.t,
    :"response_format" => String.t,
    :"query_fee" => integer(),
    :"ttl" => integer(),
    :"vm_version" => integer()
  }
end

defimpl Poison.Decoder, for: AeternityNode.Model.RegisteredOracle do

  def decode(value, options) do
    value
  end
end

