# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AeternityNode.Model.SophiaJsonData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
          :data => Object
        }
end

defimpl Poison.Decoder, for: AeternityNode.Model.SophiaJsonData do
  def decode(value, options) do
    value
  end
end
